data:
  train_path: "data/example_train.txt" 
  train_label_path: "data/example_train_labels.txt"
  test_path: "data/example_test.txt"
  test_label_path: "data/example_test_labels.txt"
  filter: "replace"
  corerate: 1

  
model:
  class_cond: True
  dropout: 0.0
  n_layer: 4
  n_head: 2
  feature_size: 16
  
diffusion:
  noise_schedule: "cosine"
  linear_start: 0.0001 
  linear_end: 0.0195
  diffusion_steps: 1000
  log_every_t: 10
  learn_sigma: False

  
train:
  lr: 0.00003
  batch_size: 32
  schedule_plot: False
